namespace E_Commerce.dto
{
    public class CartDto
    {
        public int CartId { get; set; } // Auto-generated by EF

        public int? UserId { get; set; }

        public string? Status { get; set; }
    }
}
